### PR TITLE
Updated to Angular 2 RC1.

### PR DESCRIPTION
**Pull request by MaherJendoubi**
Hi Shawn,

I updated the project to angular 2 rc1 and removed unnecessary namespaces using.

Thanks.

### CODE REVIEW

**Comment by shawnwildermuth** [comment]
I'm starting to look at merging these changes, but since you modified every C# file, it's making it difficult. Here are some questions (I'm only looking at merging the ng2 stuff, not the changes you made to the C# because all of that changed in RC2):

- When you changed the system.config.js (was called config.js) and has it looking in node_modules which isn't accessible from ASP.NET Core (must be in wwwroot). I've put them in wwwroot/lib instead.
- what is the angular2.webapi.inmemory for?

**Comment by MaherJendoubi** [comment]
Hi @shawnwildermuth I'm sorry about modifying the C# files it's was a resharper proposal (only some cleanup of unnecessary namespaces). 

* My PR is not working for the page contact because of node_modules which isn't acessible from ASP.NET Core as you said.
* I followed the [angular 2 quickstart]( https://angular.io/docs/ts/latest/quickstart.html#!#systemjs)
* https://github.com/wardbell/a2-in-memory-web-api
* I followed also this [article](http://www.mithunvp.com/angular-2-asp-net-core-visual-studio-code-typescript) for migration

**Comment by shawnwildermuth** [comment]
I updated this to RC3, I'm closing the PR.

**Comment by MaherJendoubi** [comment]
But I see RC2 : 
image

**Comment by MaherJendoubi** [comment]
image

**Pull request closed without merging**
